/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package es.externa.libreriaplumber;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
